### ISSUE TITLE
Jandex issue when upgrate to 1.0.0

### ISSUE THREAD

**Issue by oo00spy00oo** [kordamp/jandex-gradle-plugin#23]
Quarkus version: 2.11.3
Gradle: 7.5.1

```
> io.quarkus.builder.BuildException: Build failure: Build failed due to errors
  	[error]: Build step io.quarkus.deployment.index.ApplicationArchiveBuildStep#build threw an exception: org.jboss.jandex.UnsupportedVersion: Can't read index version 11; this IndexReader only supports index versions 2-3,6-10
  	at org.jboss.jandex.IndexReader.initReader(IndexReader.java:87)
  	at org.jboss.jandex.IndexReader.readVersion(IndexReader.java:140)
  	at org.jboss.jandex.IndexReader.getIndexVersion(IndexReader.java:127)
  	at io.quarkus.deployment.index.IndexingUtil$MetaInfJandexReader.apply(IndexingUtil.java:244)
  	at io.quarkus.deployment.index.IndexingUtil$MetaInfJandexReader.apply(IndexingUtil.java:230)
  	at io.quarkus.paths.PathTreeVisit.process(PathTreeVisit.java:40)
  	at io.quarkus.paths.DirectoryPathTree.apply(DirectoryPathTree.java:106)
  	at io.quarkus.paths.ArchivePathTree$OpenArchivePathTree.apply(ArchivePathTree.java:202)
  	at io.quarkus.paths.PathTreeWithManifest.apply(PathTreeWithManifest.java:73)
  	at io.quarkus.deployment.index.IndexingUtil.indexTree(IndexingUtil.java:61)
  	at io.quarkus.deployment.index.ApplicationArchiveBuildStep.lambda$addMarkerFilePaths$1(ApplicationArchiveBuildStep.java:251)
  	at io.quarkus.bootstrap.classloading.PathTreeClassPathElement.apply(PathTreeClassPathElement.java:111)
  	at io.quarkus.deployment.index.ApplicationArchiveBuildStep.addMarkerFilePaths(ApplicationArchiveBuildStep.java:2[38](https://gitlab.com/bizzi-group/bizzi-pay/bizzi-payment-backend-java/-/jobs/3038231999#L38))
  	at io.quarkus.deployment.index.ApplicationArchiveBuildStep.scanForOtherIndexes(ApplicationArchiveBuildStep.java:144)
  	at io.quarkus.deployment.index.ApplicationArchiveBuildStep.build(ApplicationArchiveBuildStep.java:105)
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:[43](https://gitlab.com/bizzi-group/bizzi-pay/bizzi-payment-backend-java/-/jobs/3038231999#L43))
  	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
  	at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:977)
  	at io.quarkus.builder.BuildContext.run(BuildContext.java:281)
  	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
  	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2[44](https://gitlab.com/bizzi-group/bizzi-pay/bizzi-payment-backend-java/-/jobs/3038231999#L44)9)
  	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1[47](https://gitlab.com/bizzi-group/bizzi-pay/bizzi-payment-backend-java/-/jobs/3038231999#L47)8)
  	at java.base/java.lang.Thread.run(Thread.java:833)
  	at org.jboss.threads.JBossThread.run(JBossThread.java:[50](https://gitlab.com/bizzi-group/bizzi-pay/bizzi-payment-backend-java/-/jobs/3038231999#L50)1)
* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
* Get more help at https://help.gradle.org/
BUILD FAILED in 7m 13s
```

**Comment by aalmiray** [comment]
Version `1.0.0` of the jandex-gradle-plugin supports Jandex `3.0.0` or greater. If you're using an older version then please upgrade.

**Comment by HerrDerb** [comment]
Same error here, with the newest version of quarkus `2.12.2.Final` and the gradle jandex plugin `version '1.0.0'`.

**Comment by aalmiray** [comment]
Then I'm afraid you need to downgrade to the previous jandex-gradle-plugin release.

**Comment by oo00spy00oo** [comment]
> 

Currently, the version `0.13.2` is fine with me and Quarkus `2.13.0.Final`
