### ISSUE TITLE
MissingPropertyException: Could not set unknown property 'sources' for task ':jandex' of type org.kordamp.gradle.plugin.jandex.tasks.JandexTask

### ISSUE THREAD

**Issue by mvysny** [kordamp/jandex-gradle-plugin#7]
The 'sources' property (as suggested by the documentation) unfortunately doesn't seem to exist. The following `build.gradle` file:

```groovy
plugins {
    id("org.kordamp.gradle.jandex") version "0.8.0"
}

jandex {
    sources = project.fileTree(dir: project.buildDir, includes: ["com/vaadin/flow/**/*.class"])
}
```

fails with:

```
Caused by: groovy.lang.MissingPropertyException: Could not set unknown property 'sources' for task ':jandex' of type org.kordamp.gradle.plugin.jandex.tasks.JandexTask.
        at org.gradle.internal.metaobject.AbstractDynamicObject.setMissingProperty(AbstractDynamicObject.java:118)
        at org.gradle.internal.metaobject.ConfigureDelegate.setProperty(ConfigureDelegate.java:104)
        at build_12tm7plxy8ai7aiiasft8wf8p$_run_closure1.doCall(/home/mavi/work/inacta/vaadin-jandex/build.gradle:34)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
```

**Comment by aalmiray** [comment]
The `sources` property is of type `ConfigurableFileCollection` -> https://github.com/kordamp/jandex-gradle-plugin/blob/master/src/main/groovy/org/kordamp/gradle/plugin/jandex/tasks/JandexTask.groovy#L59

Prior to version `0.8.0` there was a property of type `FileTree` that would let you set input files.

**Comment by mvysny** [comment]
Thank you, but it doesn't seem that there is a property named `sources` in the version 0.8.0. My Intellij shows the following sources of the `JandexTask.groovy file`:

```
class JandexTask extends DefaultTask {
    private final BooleanState processDefaultFileSet
    private final StringState indexName

    @OutputFile
    final RegularFileProperty destination = project.objects.fileProperty()
    private ConfigurableFileTree fileSets
...
```

Maybe there's a newer version of the plugin?

**Comment by aalmiray** [comment]
Version `0.9.0` has been released.

**Comment by mvysny** [comment]
Awesome, it works perfectly, thank you :)
